name: Build

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and build 🔧
        run: |
          npm install
          npm run build
      
      - name: Validate HTML
        uses: jakejarvis/html-proofer-action@v0.1.0
        with:
          directory: 'dist'
          check_html: true
  
      - name: Validate CSS
        uses: ybiquitous/stylelint-action@v2
        with:
          files: 'dist/**/*.css'
